export default {
	products: [
		{
			name: 'product a',
			catagory: 'cat a',
			price: 100,
			id: 'p-a',
			brand: 'brand a',
			description: 'something....',
			stock: 6,
			rating: 2.5,
			reviews: 100,
			image: './images/p1.jfif',
		},
		{
			name: 'product b',
			catagory: 'cat a',
			price: 35,
			id: 'p-b',
			brand: 'brand b',
			description: 'something....',
			stock: 12,
			rating: 3.5,
			reviews: 57,
			image: './images/p2.jfif',
		},
		{
			name: 'product c',
			catagory: 'cat b',
			price: 20,
			id: 'p-c',
			brand: 'brand a',
			description: 'something....',
			stock: 15,
			rating: 2.5,
			reviews: 35,
			image: './images/p3.jfif',
		},
		{
			name: 'product d',
			catagory: 'cat c',
			price: 60,
			id: 'p-d',
			brand: 'brand b',
			description: 'something....',
			stock: 7,
			rating: 4.0,
			reviews: 20,
			image: './images/p4.jfif',
		},
	],
};
