import bcrypt from 'bcryptjs';

export default {
	users: [
		{
			name: 'Admin',
			email: 'admin@example.com',
			password: bcrypt.hashSync('12345'),
		},
	],
	products: [
		{
			name: 'productA name',
			category: 'Pharma',
			price: 100,
			token: 'productA name',
			brand: 'Careline',
			description: 'product that has no description',
			stock: 6,
			rating: 2.5,
			totalReviews: 100,
			image: 'images/p1.jfif',
		},
		{
			name: 'productB name',
			category: 'Sports',
			price: 80,
			token: 'productB name',
			brand: 'Sporta',
			description: 'A sporty product',
			stock: 0,
			rating: 2.5,
			totalReviews: 100,
			image: 'images/p2.jfif',
		},
		{
			name: 'productC name',
			category: 'Pharma',
			price: 19,
			token: 'productC name',
			brand: 'Teva',
			description: 'A mediocare product',
			stock: 46,
			rating: 3,
			totalReviews: 50,
			image: 'images/p3.jfif',
		},
		{
			name: 'productD name',
			category: 'Food',
			price: 15,
			token: 'productD name',
			brand: 'BestBrand',
			description: 'A very good product',
			stock: 315,
			rating: 4.5,
			totalReviews: 452,
			image: 'images/p4.jfif',
		},
		{
			name: 'productE name',
			category: 'Pharma',
			price: 105,
			token: 'productE name',
			brand: 'BestBrand',
			description: 'A very good product',
			stock: 0,
			rating: 5,
			totalReviews: 1145,
			image: 'images/p1.jfif',
		},
		{
			name: 'productF name',
			category: 'Sports',
			price: 22,
			token: 'productF name',
			brand: 'BestBrand',
			description: 'A very good product',
			stock: 547,
			rating: 3,
			totalReviews: 7,
			image: 'images/p2.jfif',
		},
		{
			name: 'productG name',
			category: 'Pharma',
			price: 80,
			token: 'productG name',
			brand: 'BestBrand',
			description: 'A very good product',
			stock: 67,
			rating: 4.5,
			totalReviews: 101,
			image: 'images/p3.jfif',
		},
		{
			name: 'productH name',
			category: 'Food',
			price: 152,
			token: 'productH name',
			brand: 'BestBrand',
			description: 'A very good product',
			stock: 315,
			rating: 4,
			totalReviews: 84,
			image: 'images/p4.jfif',
		},
	],
};
